/**
 * PITMAN SHORTHAND STROKE LIBRARY
 * 
 * Extracted from official Pitman Shorthand reference materials.
 * Each stroke contains:
 * - Visual description from AI analysis
 * - Sound representation (phonetic)
 * - Example words
 * - Category classification
 * - Reference to source material
 * 
 * Generated by: scripts/extract_individual_strokes.py
 */

export interface Stroke {
  id: string;
  name: string;
  sound: string;
  phonetic?: string;
  category: 'STRAIGHT_DOWN' | 'CURVED' | 'HORIZONTAL' | 'UPWARD' | 'SPECIAL';
  visual: string;
  direction: string;
  weight: 'Light' | 'Heavy' | 'Heavy/Thick';
  description: string;
  examples: string[];
  sourceReference?: string;
  strokeSymbol: string; // The actual shorthand representation (legacy)
  svgPath?: string; // Path to SVG file for proper rendering
}

export const STROKE_LIBRARY: Stroke[] = [
  {
    id: 'P',
    name: 'P',
    sound: 'p',
    category: 'STRAIGHT_DOWN',
    visual: 'Light straight line written downward',
    direction: 'Downward vertical',
    weight: 'Light',
    description: 'Short light vertical stroke for the sound "p"',
    examples: ['pay', 'put', 'paper'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╲' // Light upward diagonal (p/b)
  },
  {
    id: 'B',
    name: 'B',
    sound: 'b',
    category: 'STRAIGHT_DOWN',
    visual: 'Heavy straight line written downward',
    direction: 'Downward vertical',
    weight: 'Heavy/Thick',
    description: 'Short heavy vertical stroke for the sound "b"',
    examples: ['bay', 'but', 'baby'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╲' // Heavy upward diagonal (p/b)
  },
  {
    id: 'T',
    name: 'T',
    sound: 't',
    category: 'STRAIGHT_DOWN',
    visual: 'Light straight line written downward (longer than P)',
    direction: 'Downward vertical',
    weight: 'Light',
    description: 'Medium-length light vertical stroke for the sound "t"',
    examples: ['tea', 'time', 'table'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⟊' // Light curve (t/d)
  },
  {
    id: 'D',
    name: 'D',
    sound: 'd',
    category: 'STRAIGHT_DOWN',
    visual: 'Heavy straight line written downward (longer than B)',
    direction: 'Downward vertical',
    weight: 'Heavy/Thick',
    description: 'Medium-length heavy vertical stroke for the sound "d"',
    examples: ['day', 'do', 'data'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⟊' // Heavy curve (t/d)
  },
  {
    id: 'CH',
    name: 'CH',
    sound: 'ch',
    category: 'STRAIGHT_DOWN',
    visual: 'Light straight line written downward (longer than T)',
    direction: 'Downward vertical',
    weight: 'Light',
    description: 'Long light vertical stroke for the sound "ch"',
    examples: ['chair', 'church', 'reach'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╱' // Light upward diagonal (ch/j)
  },
  {
    id: 'J',
    name: 'J',
    sound: 'j',
    category: 'STRAIGHT_DOWN',
    visual: 'Heavy straight line written downward (longest)',
    direction: 'Downward vertical',
    weight: 'Heavy/Thick',
    description: 'Long heavy vertical stroke for the sound "j"',
    examples: ['jay', 'judge', 'jar'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╱' // Heavy upward diagonal (ch/j)
  },
  {
    id: 'F',
    name: 'F',
    sound: 'f',
    category: 'CURVED',
    visual: 'Light curve opening to the right',
    direction: 'Downward curve',
    weight: 'Light',
    description: 'Gentle curve opening to the right for the sound "f"',
    examples: ['far', 'feed', 'funny'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╱', // ef - shallow curve (legacy)
    svgPath: require('../assets/stroke-svgs/F.svg')
  },
  {
    id: 'V',
    name: 'V',
    sound: 'v',
    category: 'CURVED',
    visual: 'Heavy curve opening to the right',
    direction: 'Downward curve',
    weight: 'Heavy/Thick',
    description: 'Thick curve opening to the right for the sound "v"',
    examples: ['very', 'voice', 'value'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╱' // vee - shallow curve (heavy)
  },
  {
    id: 'ITH',
    name: 'ITH',
    sound: 'ith',
    phonetic: 'voiceless th',
    category: 'CURVED',
    visual: 'Light curve opening to the left',
    direction: 'Downward curve',
    weight: 'Light',
    description: 'Gentle curve opening to the left for the sound "th" as in "thin"',
    examples: ['thin', 'think', 'path'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╲' // ith - shallow curve opposite
  },
  {
    id: 'THE',
    name: 'THE',
    sound: 'the',
    phonetic: 'voiced th',
    category: 'CURVED',
    visual: 'Heavy curve opening to the left',
    direction: 'Downward curve',
    weight: 'Heavy/Thick',
    description: 'Thick curve opening to the left for the sound "th" as in "this"',
    examples: ['this', 'that', 'the'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '╲' // thee - shallow curve opposite (heavy)
  },
  {
    id: 'S',
    name: 'S',
    sound: 's',
    category: 'CURVED',
    visual: 'Small left-facing curve',
    direction: 'Downward curve',
    weight: 'Light',
    description: 'Small gentle curve opening to the left for the sound "s"',
    examples: ['say', 'see', 'sun'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⌢' // ess - medium curve
  },
  {
    id: 'Z',
    name: 'Z',
    sound: 'z',
    category: 'CURVED',
    visual: 'Heavy left-facing curve',
    direction: 'Downward curve',
    weight: 'Heavy',
    description: 'Thick curve opening to the left for the sound "z"',
    examples: ['zoo', 'zero', 'zeal'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⌢' // zee - medium curve (heavy)
  },
  {
    id: 'ISH',
    name: 'ISH',
    sound: 'ish',
    phonetic: 'sh sound',
    category: 'CURVED',
    visual: 'Light deep curve',
    direction: 'Downward curve',
    weight: 'Light',
    description: 'Deep gentle curve for the sound "sh"',
    examples: ['she', 'ship', 'wash'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⟌' // ishi - deep curve
  },
  {
    id: 'ZHEE',
    name: 'ZHEE',
    sound: 'zhee',
    phonetic: 'zh sound',
    category: 'CURVED',
    visual: 'Heavy deep curve',
    direction: 'Downward curve',
    weight: 'Heavy',
    description: 'Deep heavy curve for the sound "zh" as in "measure"',
    examples: ['measure', 'pleasure', 'vision'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⟌' // zhee - deep curve (heavy)
  },
  {
    id: 'K',
    name: 'K',
    sound: 'k',
    category: 'HORIZONTAL',
    visual: 'Light horizontal line left to right',
    direction: 'Horizontal',
    weight: 'Light',
    description: 'Short light horizontal stroke for the sound "k"',
    examples: ['key', 'keep', 'kid'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '—' // Light horizontal (k)
  },
  {
    id: 'G',
    name: 'G',
    sound: 'g',
    category: 'HORIZONTAL',
    visual: 'Heavy horizontal line left to right',
    direction: 'Horizontal',
    weight: 'Heavy',
    description: 'Thick horizontal stroke for the sound "g"',
    examples: ['go', 'give', 'good'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '━' // Heavy horizontal (g)
  },
  {
    id: 'M',
    name: 'M',
    sound: 'm',
    category: 'HORIZONTAL',
    visual: 'Light horizontal hook',
    direction: 'Horizontal left to right',
    weight: 'Light',
    description: 'Short light horizontal hook for the sound "m"',
    examples: ['me', 'make', 'more'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⌒' // Horizontal hook (m)
  },
  {
    id: 'N',
    name: 'N',
    sound: 'n',
    category: 'UPWARD',
    visual: 'Light upward diagonal stroke',
    direction: 'Upward 45° left to right',
    weight: 'Light',
    description: 'Straight line written upward diagonally for the sound "n"',
    examples: ['no', 'name', 'never'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⌣' // Light curve (n)
  },
  {
    id: 'NG',
    name: 'NG',
    sound: 'ng',
    category: 'UPWARD',
    visual: 'Heavy upward diagonal stroke',
    direction: 'Upward 45° left to right',
    weight: 'Heavy',
    description: 'Thick line written upward diagonally for the sound "ng"',
    examples: ['sing', 'long', 'bring'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '⌣' // Heavy curve (ng)
  },
  {
    id: 'L',
    name: 'L',
    sound: 'l',
    category: 'UPWARD',
    visual: 'Upward stroke',
    direction: 'Upward vertical',
    weight: 'Light',
    description: 'Vertical line written upward for the sound "l"',
    examples: ['let', 'like', 'love'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '|' // Upward vertical (l)
  },
  {
    id: 'W',
    name: 'W',
    sound: 'w',
    category: 'UPWARD',
    visual: 'Light upward curve',
    direction: 'Upward curve',
    weight: 'Light',
    description: 'Curved stroke written upward',
    examples: ["way", "away", "wow"],
    sourceReference: 'page_012.png',
    strokeSymbol: '∪' // Light upward curve (w)
  },
  {
    id: 'Y',
    name: 'Y',
    sound: 'y',
    category: 'UPWARD',
    visual: 'Light upward curve (smaller than W)',
    direction: 'Upward curve',
    weight: 'Light',
    description: 'Small curved stroke written upward',
    examples: ["yay", "yes", "you"],
    sourceReference: 'page_012.png',
    strokeSymbol: '∩' // Diphthong upside down
  },
  {
    id: 'R',
    name: 'R',
    sound: 'r',
    category: 'UPWARD',
    visual: 'Upward or downward curved stroke',
    direction: 'Variable - upward or downward',
    weight: 'Light',
    description: 'Curved stroke, direction depends on context (upward or downward)',
    examples: ["ray", "bar", "rarer"],
    sourceReference: 'page_034.png',
    strokeSymbol: '~' // Variable curve (r)
  },
  {
    id: 'H',
    name: 'H',
    sound: 'h',
    category: 'SPECIAL',
    visual: 'Dot',
    direction: 'N/A - dot',
    weight: 'Light',
    description: 'Small dot placed at the beginning of the stroke',
    examples: ['he', 'him', 'who'],
    sourceReference: 'AI Analysis - Page 9, Consonant Alphabet',
    strokeSymbol: '·' // Dot
  },
];

// Category groups for easy filtering
export const STROKE_CATEGORIES = {
  STRAIGHT_DOWN: STROKE_LIBRARY.filter(s => s.category === 'STRAIGHT_DOWN'),
  CURVED: STROKE_LIBRARY.filter(s => s.category === 'CURVED'),
  HORIZONTAL: STROKE_LIBRARY.filter(s => s.category === 'HORIZONTAL'),
  UPWARD: STROKE_LIBRARY.filter(s => s.category === 'UPWARD'),
  SPECIAL: STROKE_LIBRARY.filter(s => s.category === 'SPECIAL'),
};

// Get stroke by ID
export function getStroke(id: string): Stroke | undefined {
  return STROKE_LIBRARY.find(s => s.id === id);
}

// Get strokes by sound
export function getStrokesBySound(sound: string): Stroke[] {
  return STROKE_LIBRARY.filter(s => s.sound === sound);
}

// Weight pairs (light/heavy)
export const WEIGHT_PAIRS = [
  { light: 'F', heavy: 'V' },
  { light: 'ITH', heavy: 'THE' },
  { light: 'S', heavy: 'Z' },
  { light: 'ISH', heavy: 'ZHEE' },
  { light: 'N', heavy: 'NG' },
  { light: 'P', heavy: 'B' },
  { light: 'T', heavy: 'D' },
  { light: 'CH', heavy: 'J' },
  { light: 'K', heavy: 'G' },
];

// Mirror pairs (direction)
export const MIRROR_PAIRS = [
  { right: 'F', left: 'ITH', weight: 'light' },
  { right: 'V', left: 'THE', weight: 'heavy' },
];

// Depth comparison (shallow to deep)
export const CURVE_DEPTHS = {
  shallow: ['S', 'Z'],
  moderate: ['F', 'V', 'ITH', 'THE'],
  deep: ['ISH', 'ZHEE'],
};
